#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LiarsDice.Resource", IsApplication=true)]

namespace LiarsDice
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Five_side = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Four_side = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int One_side = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RemoveDie = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int roll_dice = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Six_side = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Three_side = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Two_side = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int unknown = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int CheatBtn = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int Die1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Die2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Die3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int Die4 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int Die5 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int HideToggleBtn = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int RemoveDieBtn = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int ResetBtn = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int RollDiceBtn = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout2 = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int curtain = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int DICE = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int gasps = 2131034114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int roll = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
